package no.nav.tiltakspenger.utbetaling.domene

import java.time.LocalDate
import java.util.*

data class Utbetaling(
    val sakId: SakId,
    val utløsendeMeldekortId: String,
    val utbetalingDager: List<UtbetalingDag>,
    val saksbehandler: String,
)

data class UtbetalingDag(
    val dato: LocalDate,
    val tiltaktype: TiltakType,
    val status: UtbetalingDagStatus,
    val meldekortId: UUID,
    val løpenr: Int,
)

enum class UtbetalingDagStatus {
    IngenUtbetaling,
    FullUtbetaling,
    DelvisUtbetaling,
}

enum class TiltakType {
    AMBF1,
    ABOPPF,
    ABUOPPF,
    ABIST,
    ABTBOPPF,
    ARBFORB,
    AMO,
    AMOE,
    AMOB,
    AMOY,
    PRAKSORD,
    PRAKSKJERM,
    ARBRRHBAG,
    ARBRRHBSM,
    ARBRRHDAG,
    ARBRDAGSM,
    ARBRRDOGN,
    ARBDOGNSM,
    ARBTREN,
    AVKLARAG,
    AVKLARUS,
    AVKLARSP,
    AVKLARKV,
    AVKLARSV,
    DIGIOPPARB,
    ENKELAMO,
    ENKFAGYRKE,
    KAT,
    VALS,
    FORSAMOENK,
    FORSFAGENK,
    FORSHOYUTD,
    FUNKSJASS,
    GRUPPEAMO,
    GRUFAGYRKE,
    HOYEREUTD,
    INDJOBSTOT,
    IPSUNG,
    INDOPPFOLG,
    INKLUTILS,
    JOBBKLUBB,
    JOBBFOKUS,
    JOBBK,
    JOBBBONUS,
    MENTOR,
    NETTAMO,
    INDOPPFAG,
    INDOPPFSP,
    INDOPPRF,
    REFINO,
    SPA,
    SUPPEMP,
    TILPERBED,
    UTDYRK,
    UTBHLETTPS,
    UTBHPSLD,
    UTBHSAMLI,
    UTVAOONAV,
    UTVOPPFOPL,
    OPPLT2AAR,
    FORSOPPLEV,
    UTEN_TILTAK,
}
